### ISSUE TITLE
Alpha support

### ISSUE THREAD

**Issue by LinuxUserGD** [Bauxitedev/godot-motion-blur#1]
Nice plugin!
Currently alpha transparency doesn't work if the .tscn file is attached to the camera --> object isn't rendered
Not sure how to change albedo_color to .rgba in the shader.

**Comment by Bauxitedev** [comment]
Not sure what you mean by this. Do you want to have motion blur on transparent objects? If so, that won't work, because the shader uses the depth buffer to get the 3D position of a pixel, and transparent objects aren't written to the depth buffer.

**Comment by LinuxUserGD** [comment]
The half transparent objects disappear, even if the camera doesn't move.

**Comment by Bauxitedev** [comment]
I see, I've changed the rendering priority and it seems to work for me now. Can you test it again with the newest changes?

**Comment by LinuxUserGD** [comment]
Yes, now it's working :+1:

**Comment by LinuxUserGD** [comment]
@Bauxitedev "in a racing game you'll notice the car will be blurred in the same way as the environment."

A workaround could be to pick the transparent flag in the material option of the car and set the depth draw mode to always.

**Comment by Bauxitedev** [comment]
Good idea, I'll put that in the readme.
