### ISSUE TITLE
Quat Wrap/Jump Issue and Fix

### ISSUE THREAD

**Issue by PolyVector** [Bauxitedev/godot-motion-blur#11]
I just noticed an issue where the cam_rot_diff value jumps when camera's euler angles flip back around for a single frame.  This creates a large blur in the opposite direction for just that frame.  I'm not great with math, but luckily I do know a fix from working with quats in other areas.

You simply need to compare the 2 quats you are subtracting with a dot product, and negate if the result is negative:

```
	var cam_rot_diff = cam_rot - cam_rot_prev
	if cam_rot.dot(cam_rot_prev) < 0.0: # Wraparound Fix
		cam_rot_diff = -cam_rot_diff;
```

**Edit:** The idea behind this is that sometimes the difference between 2 quats can be "the long way around" instead of the short.  Think 350 degrees instead of -10.  Negating a quat fixes this.

I hope this helps. :)

**Comment by Bauxitedev** [comment]
I haven't seen this issue occur in practice, but I'll take your word for it.
