### ISSUE TITLE
Great Shader!

### ISSUE THREAD

**Issue by padreputativo** [Bauxitedev/godot-motion-blur#8]
Can you convert it to a TextureRect and put it inside the addon's folder? It would great!

It would replicate this behaviour:
https://godotengine.org/asset-library/asset/122

**Comment by Bauxitedev** [comment]
Unfortunately this is not possible at the moment, since canvas (screen space) shaders in Godot cannot currently access the depth buffer, only spatial shaders can. 

The add-ons folder thing is a good idea, I'll have to do that at some point.

**Comment by doradoro** [comment]
Many thanks!

**Comment by padreputativo** [comment]
Many thanks!
